- name: "Create virtual machine {{ vm_template.id }} / {{ vm_template.hostname }}"
  proxmox:
    vmid: "{{ vm_template.id }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_cluster_host }}"
    node: "{{ proxmox_node }}"
    pool: "{{ proxmox_pool }}"
    vcpus: "{{ vm_template.cpus }}"
    memory: "{{ vm_template.memory }}"
    netif: {'net0': "virtio,bridge=vmbr1"}
    sata: "{'sata0': 'local:{{ vm_template.disk }},format=qcow2' }"
    ide: "{'ide0': 'template:iso/{{ vm_template.iso }},media=cdrom' }"
    template: True
    state: present
