- name: "Stop container {{ hostname }}"
  proxmox:
    hostname: "{{ hostname }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_cluster_host }}"
    node: "{{ proxmox_node }}"
    pool: "{{ proxmox_pool }}"
    force: yes
    state: stopped
- name: "Remove container {{ hostname }}"
  proxmox:
    hostname: "{{ hostname }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ proxmox_cluster_host }}"
    node: "{{ proxmox_node }}"
    pool: "{{ proxmox_pool }}"
    state: absent
