#+TITLE: Playbook =add-virtual-machine=
* Synopsis
  #+begin_src shell
    ansible-playbook -i <inventory> add-virtual-machine.yml -e "vm_def_file=<definition_file.yml>"
  #+end_src
* Description
  This playbook allows to create a virtual machine with one disk and
  one network interface, on a proxmox virtualization environment.

  - =<inventory>=, the path to the inventory file referencing the
    proxmox REST API entry-point host.
  - =<definition_file.yml>=, the path to a file describing the
    virtual machine to create.

  Creation steps:
  - Calling proxmox to reserve the necessary resources to create the
    VM
    - CPU.
    - Memory.
    - The Network interface.
    - Attaching the ISO file as a CD-ROM (see below for details).
  - Creation of the disk.
  - Attaching the disk to the VM as resource =sata0=.
  - Start the virtual machine.

  If the =<inventory>= file contains more than the proxmox REST API
  entry-point host, use the =--limit= option to restrict the list of
  hosts to loop over for the play.

  You need to connect to the host with a user that have the correct
  permission to administer the proxmox cluster.

  The user must have, at least, the following permission:
  - Can access the REST API entry-point.
  - Can run pve* commands.
  - Can run QEMU commands.

  The following variables needs to be defined for the connection to
  the proxmox REST API:
  - =proxmox_cluster_host=: The host of the proxmox cluster to send
    requests to.
  - =proxmox_node=: The node where the VM must be created.
  - =proxmox_user=: The proxmox user that will perform the action.
  - =proxmox_password=: the proxmox user's password.
  - =proxmox_pool=: The proxmox resource pool where the VM will be
    affected.

  As those variables will not change across runs, a good place to set
  them is in the =host_vars= file of the proxmox host. The only
  exception is =proxmox_pool=, each VM can be in a different resource
  pool, following there usage.

  Example of =host_vars= file content:
  #+begin_src yaml
    proxmox_cluster_host: localhost
    proxmox_node: node1
    proxmox_user: root@pam
    proxmox_password: "my secret pwd"
    proxmox_pool: "cesspool"
  #+end_src

  The content of =<definition_file.yml>= is limited to the following
  variables:
  - =hostname=: The name of the VM to create (only used in the
    proxmox webconsole).
  - =cpus=: The number of cpus to allocate to the VM.
  - =memory=: The size of the memory (in Mb) to allocate to the VM.
  - =disk_size=: The size of the root disk (in Gb).
  - =iso=: The name of the ISO file to use to create the VM.
  - =storage=: The name of the proxmox storage to use to host the
    root disk.

  The ISO file specified will be used to start the process of
  installation of the OS. This process could require interaction with
  the user, for a workstation installation for example, so you will
  need a connection to the console of the VM.

  Example of VM definition file content:
  #+begin_src yaml
    ---
    hostname: vm-fc31-wks-test
    cpus: 1
    memory: 2048
    disk_size: "20"
    iso: "Fedora-Xfce-Live-x86_64-31-1.9.iso"
    storage: local
  #+end_src
* Author

+ Roland Everaert
* Copyright

Copyright (c) 2020 Roland Everaert
