---
- hosts: all
  gather_facts: False
  tasks:
    - name: Get Virtual Machine definition from file
      include_vars:
        file: "{{ vm_def_file }}"
        name: vm_tpl
    - name: "Create virtual machine {{ vm_tpl.hostname }} in proxmox - Cluster {{ proxmox_cluster_host }} / Node {{ proxmox_node }}"
      include_role:
        name: vm-management
        tasks_from: add-vm
