---
- hosts: all
  gather_facts: False
  tasks:
    - name: "Remove container {{ hostname }} from Proxmox - Cluster {{ proxmox_cluster_host }} / Node {{ proxmox_node }}"
      include_role:
        name: ct-managment
        tasks_from: rm-ct
