---
- hosts: all
  gather_facts: False
  tasks:
    - name: "Remove virtual machine from Proxmox - Cluster {{ proxmox_cluster_host }} / Node {{ proxmox_node }}"
      include_role:
        name: vm-management
        tasks_from: rm-vm
